init:
	gcc init.c -o init.o
shutdown:
	gcc shutdown.c -o shutdown.o
create:
	gcc create.c -o create.o
destroy:
	gcc destroy.c -o destroy.o
count:
	gcc count.c -o count.o
send:
	gcc send.c -o send.o
recv:
	gcc recv.c -o recv.o
length:
	gcc length.c -o length.o
add_acl:
	gcc add_acl.c -o add_acl.o
rem_acl:
	gcc rem_acl.c -o rem_acl.o
clean:
	rm *.o
